### ISSUE TITLE
Fix overflow at incidents page

### ISSUE THREAD

**Issue by froi** [eluciano11/AEEIncidentsFrontend#2]
There's an overflow bug in the incidents page in the town list.
![town list overflow](https://cloud.githubusercontent.com/assets/1918027/5606673/307b5e3e-9410-11e4-9457-b07b48c0f924.png)

**Comment by ens-labs** [comment]
For now it's indeed working. But test it,

**Comment by ens-labs** [comment]
Fixed it. Check it out,
