### ISSUE TITLE
Code for the side nav height

### ISSUE THREAD

**Issue by froi** [eluciano11/AEEIncidentsFrontend#4]
¿Alguna razón para este código en index.html?

``` javascript
$(document).ready(function(){
   ele = document.getElementById('home');
   var heighty = $(window).height();;
   ele.style.height = heighty + 'px';
});
```

Hace su trabajo pero una vez la pagina hace load el sidebar no crece o se achica. Para mi se le debe de poner un css class con `height: 100%`.

¿Qué creen?
### Edit

This is what I mean:
![screen shot 2015-02-27 at 4 29 02 pm](https://cloud.githubusercontent.com/assets/1918027/6420621/00329a9a-be9e-11e4-9912-5dcb4486f4af.png)
That space in the bottom should be filled with the sidebar.

**Comment by eluciano11** [comment]
Yo entiendo que solo funciona cuando se hace load por el document ready. Ese cambio lo hizo @ens-labs. Antes teníamos 'height:100vh'. Según el viewport height del usuario iba a ser el largo del navbar. No se si el 100% funcione en el height, lo he tratado en otras ocaciones y no me ha bregado.

**Comment by froi** [comment]
El 100% va a depender del tamaño de su container. Si su container tiene un valor absoluto de height esto lo llenara completo. Nada lo pruebo y vemos que pasa.

**Comment by froi** [comment]
Por cierto, valores absolutos se deben de obviar a menos que sea min-\* o max-\* o que sea por diseño. Esto ayuda a que sea más responsive.

**Comment by ens-labs** [comment]
Lo que pasa es que cuando ponia el height en 100% algo me explotaba. Y decidir calcular el respectivo height de acuerdo al tamaño de pantalla incluyendo el imagen que cambia de tamaño dependiendo de la pantalla. Also, si cambias el tamaño del browser, ese sidebar hace resize, y el código está en "dynamic-list.js". No sé, eso fue lo que se me ocurrió hacer.

**Comment by ens-labs** [comment]
Ah y ese que está en el index.html es para el background azul que aparece en el root del website "/", Por que yo le ponia 100% y se hacia mierda. Me moleste y escribí eso para que se encargue de eso.

**Comment by ens-labs** [comment]
También estoy pensando en añadirle la parte de resize pero ahí entra la flojera.

**Comment by Bryan1010** [comment]
estoy trabajando con los devices <= 767px (smartphone width) 
lo que estoy haciendo le estoy dando constantemente push

Tambien no se si a ustedes les pasa pero cuando un municipio tiene mas de 3 averias la tabla se distorciona y rompe el height de la pagina
![aeeinsidents bug](https://cloud.githubusercontent.com/assets/6621193/6462942/126dcac0-c184-11e4-826f-bcf51f1bf2e5.png)
me refiero a esto

**Comment by ens-labs** [comment]
Se supone que eso no pase...

---

Daniel Del Río

## Sent from my iPhone

**Comment by Bryan1010** [comment]
Eso pasa es las coputadoras de 15 pulgadas
Me paso en todas las laptops de casa hasta cuando lo accesaba de heroku

**Comment by ens-labs** [comment]
Eso fue Emmanuel xD

---

Daniel Del Río

## Sent from my iPhone

**Comment by froi** [comment]
Old issue is old. I'm closing this out. 👋🏼
